### ISSUE TITLE
2022.7 Breaking Change

### ISSUE THREAD

**Issue by AnthonyMaiorani** [bjhiltbrand/drone_mobile_home_assistant#18]
Reported in Home Assistant Logs:

Temperature sensor (<class 'custom_components.drone_mobile.sensor.CarSensor'>) does not inherit SensorEntity, this will be unsupported in Home Assistant Core 2022.7. Please report it to the custom component author.

**Comment by bjhiltbrand** [comment]
While I don't see this specific error in my logs, I did fix a similar issue with regards to sensors in 2022.7. Please download the latest code and give it a shot.

**Comment by AnthonyMaiorani** [comment]
All is good now, thanks! 

The error popped up in 2022.6.7 for me and doesn't show in 2022.7, so that's why it might not have shown for you. And thanks for the imperial fix too, I was about to mention that haha.
