### ISSUE TITLE
Where is the user data stored

### ISSUE THREAD

**Issue by fischgeek** [bjhiltbrand/drone_mobile_home_assistant#25]
I'm curious about this integration. It requires my username/password. Where are these credentials stored and is it safe to use?

**Comment by fischgeek** [comment]
Awesome. Thanks. Where can I find out more information for this unofficial API? I'm a .net developer and have a couple use-cases I'd like to explore.

**Comment by fischgeek** [comment]
Impressive. Did you use wireshark or something like that?

**Comment by bjhiltbrand** [comment]
Yep.

**Comment by fischgeek** [comment]
I want to learn how to do that. Can you teach me?

**Comment by bjhiltbrand** [comment]
I don't know a lot, but on Windows, I just use Fiddler classic (https://www.telerik.com/download/fiddler). Do not click the button to "try fiddler everywhere". While, that version is super simple to use, it is their premium paid version, and they make it kind of difficult to get the free classic version. To get classic, you need to fill out the form on the left of the page and then click the "Download for Windows" button. Once you have it installed with the proper certificates installed to sniff traffic, you can then simply turn on sniffing and then navigate to the site you want to sniff and perform the actions that you want to capture. Once you're done, you just turn off sniffing in Fiddler and start reviewing the captured requests. From there, it's really just clicking on the various requests and studying them to see what flow the app takes, what requests are made with what headers and authentication schemas, and what responses are returned with what encoding. Here is the documentation for Fiddler: https://docs.telerik.com/fiddler/configure-fiddler/tasks/installfiddler
